# VLR Stats
VCT_STATS_FIELDS = [
    "player_id",
    "player",
    "org",
    "agents",
    "rounds_played",
    "rating",
    "average_combat_score",
    "kill_deaths",
    "kill_assists_survived_traded",
    "average_damage_per_round",
    "kills_per_round",
    "assists_per_round",
    "first_kills_per_round",
    "first_deaths_per_round",
    "headshot_percentage",
    "clutch_success_percentage",
    "clutches_won_played_ratio",
    "max_kills_in_single_map",
    "kills",
    "deaths",
    "assists",
    "first_kills",
    "first_deaths",
]

VLR_REQUEST_HEADER = {
    "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0",
}


region = {
    "na": "north-america",
    "eu": "europe",
    "ap": "asia-pacific",
    "la": "latin-america",
    "la-s": "la-s",
    "la-n": "la-n",
    "oce": "oceania",
    "kr": "korea",
    "mn": "mena",
    "gc": "gc",
    "br": "Brazil",
    "cn": "china",
    "jp": "japan",
    "cg": "collegiate",
}

# https://www.vlr.gg/stats/?event_group_id=3&region=na&min_rounds=800&min_rating=2000&agent=all&map_id=all&timespan=all
# event_group_id
# region
# agent
# map_id

# event_group_id
# VLR_STATS_EVENT_SERIES_MAX_ID = 89
VLR_STATS_EVENT_SERIES_MAX_ID = 2

# agent
VLR_AGENTS = [
    # "astra",
    # "breach",
    # "brimstone",
    # "chamber",
    # "clove",
    # "cypher",
    # "deadlock",
    # "fade",
    # "gekko",
    # "harbor",
    # "iso",
    "jett",
    # "kayo",
    # "killjoy",
    # "neon",
    # "omen",
    # "phoenix",
    # "raze",
    # "reyna",
    "sage",
    # "skye",
    # "sova",
    # "tejo",
    # "veto",
    # "viper",
    # "vyse",
    # "waylay",
    # "yoru",
]

# region
VLR_REGIONS = [
    "na",
    "eu",
    # "br",
    # "ap",
    # "kr",
    # "cn",
    # "jp",
    # "las",
    # "lan",
    # "oce",
    # "mn",
    # "gc",
    # "cg",
]

# map_id
VLR_REGIONS_DICT = {
    "na": "North America",
    "eu": "Europe",
    "br": "Brazil",
    "ap": "Asia-Pacific",
    "kr": "Korea",
    "cn": "China",
    "jp": "Japan",
    "las": "Latin America South",
    "lan": "Latin America North",
    "oce": "Oceania",
    "mn": "MENA",
    "gc": "Game Changers",
    "cg": "Collegiate",
}

VLR_MAPS = {
    1: "bind",
    2: "haven",
    # 3: "split",
    # 5: "ascent",
    # 6: "icebox",
    # 8: "breeze",
    # 9: "fracture",
    # 10: "pearl",
    # 11: "lotus",
    # 12: "sunset",
    # 13: "abyss",
    # 14: "corrode",
}


VLR_EVENTS_DICT = {
    89: "valorant_champions_tour_partner_series_2026",
    88: "txg_valorant_circuit",
    87: "valorant_game_changers_2026",
    86: "valorant_champions_tour_2026",
    85: "valorant_challengers_league_2026",
    84: "braza",
    83: "evc_surge_series",
    82: "exitlag",
    81: "college_valorant_2024_2025",
    80: "valorant_champions_tour_partner_series_2025",
    79: "project_v_2025",
    78: "valorant_china_evolution_series_2025",
    77: "hyperx_momentum_series",
    76: "valorant_game_changers_2025",
    75: "valorant_challengers_league_2025",
    74: "valorant_champions_tour_2025",
    73: "riot_games_one",
    72: "yfp_lockdown_arena",
    70: "beacon_national_leagues",
    69: "valorant_champions_tour_off_season_2024",
    67: "cbvl_mllse",
    66: "raidiant_academy",
    65: "norwegian_valorant_league",
    64: "project_v_2024",
    63: "valorant_east_united_2024",
    62: "valorant_game_changers_2024",
    61: "valorant_champions_tour_2024",
    60: "funhavergg",
    59: "valorant_challengers_league_2024",
    58: "flyquest_trailblazer_series",
    57: "college_valorant_2023_2024",
    56: "saudi_eleague",
    55: "community_gaming",
    54: "golden_goose",
    51: "super_girl_gamer_pro",
    50: "insomnia_iseries",
    49: "a1_esports_valorant_cup",
    48: "valorant_champions_tour_off_season_2023",
    47: "valorant_china_evolution_series_2023",
    46: "return_of_the_titans",
    45: "valorant_champions_tour_2023",
    44: "collegiate_esports_commissioners_cup",
    43: "mystic_singularity_series",
    42: "beacon_circuit_2023",
    41: "fgc_valorant_series_2023",
    40: "project_v_2023",
    39: "trinity_trials",
    38: "valorant_game_changers_2023",
    37: "valorant_east_united_2023",
    36: "red_bull_campus_clutch",
    35: "nerd_street_valorant_lockdown",
    34: "blast_spike_nations",
    33: "college_valorant_2022_2023",
    32: "valorant_champions_tour_off_season_2022",
    31: "valorant_challengers_league_2023",
    30: "nom_invitationals",
    29: "valorant_balkan_league",
    28: "the_esports_club_challenger_series",
    27: "fgc_valorant_series_2022",
    26: "beacon_circuit_2022",
    25: "project_v_2022",
    24: "valorant_east_united_2022",
    23: "knights_sakura_cup",
    22: "liga_gamers_club_serie_a",
    21: "knights_gauntlet_circuit_2022",
    20: "nerd_street_summer_championship_2022",
    19: "knights_weekly",
    17: "valorant_game_changers_2022",
    15: "valorant_regional_leagues_2022",
    14: "valorant_champions_tour_2022",
    13: "nerd_street_gamers_winter_championship",
    12: "valorant_open_tour_france",
    11: "nerd_street_gamers_summer_championship_2021",
    10: "vanguard_championship_series",
    9: "circuito_tormenta",
    8: "valorant_game_changers_2021",
    7: "nice_cactus_monthly_trophy",
    6: "knights_monthly_gauntlet",
    5: "nerd_street_gamer_monthly",
    3: "valorant_champions_tour_2021",
    2: "first_strike",
    1: "ignition_series",
}
